"""Add profile and settings fields to User model

Revision ID: eea3290190cc
Revises: 
Create Date: 2024-01-25 17:03:45.123456

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = 'eea3290190cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('email_notifications', sa.Boolean(), nullable=True, server_default='1'))
        batch_op.add_column(sa.Column('sms_notifications', sa.Boolean(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('theme', sa.String(length=20), nullable=True, server_default='light'))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.text('CURRENT_TIMESTAMP')))

    # Update existing users to have a created_at date
    op.execute("UPDATE user SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('theme')
        batch_op.drop_column('sms_notifications')
        batch_op.drop_column('email_notifications')
        batch_op.drop_column('profile_picture')
    # ### end Alembic commands ###
